name: Deploy apps/web to Hugging Face Space
on:
  push:
    branches: [feature/fastapi-server]        # change if you deploy from another branch
  workflow_dispatch:        # lets you run it manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with LFS)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push subfolder apps/web to Space repo
        env:
          HF_USERNAME: HelloWorld47474747
          SPACE_NAME: ScanServer
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git subtree split --prefix=apps/web -b space-deploy
          git push -f https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME space-deploy:main
